<a href="https://colab.research.google.com/github/sabbir2014/tean08---CSE327/blob/main/cse425.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing dependencies

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import DBSCAN

Data Collection and Analysis

In [2]:
# loading the data from csv file to a pandas dataframe
Accidents = pd.read_csv('/content/Accidents.csv')

In [3]:
# first five rpws in the dataframe
Accidents.head()

  Reference Number  Grid Ref: Easting  ...  Sex of Casualty 7  Age of Casualty 7
0          6140231             398364  ...                NaN                NaN
1          6142035             407438  ...                NaN                NaN
2          6170291             409015  ...                NaN                NaN
3          6180214             409646  ...                NaN                NaN
4          6191021             407754  ...                NaN                NaN

[5 rows x 45 columns]

In [4]:
# last five rows in the dataframe
Accidents.tail()

    Reference Number  Grid Ref: Easting  ...  Sex of Casualty 7  Age of Casualty 7
266          6CI1555             407591  ...                NaN                NaN
267          6CJ0277             398516  ...                NaN                NaN
268          6CN1273             390917  ...                NaN                NaN
269          6CS0418             406993  ...                NaN                NaN
270          6CS1526             414057  ...                NaN                NaN

[5 rows x 45 columns]

In [6]:
# finding the number of rows and columns
Accidents.shape

(271, 45)